# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 18:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCompile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.IntegerField(choices=[(1, 'C'), (2, 'Python'), (3, 'Ruby'), (4, 'Java')])),
                ('source', models.TextField()),
                ('test_cases', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeCompileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('time', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_correct', models.BooleanField()),
                ('code_compile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code_checker.CodeCompile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
