# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecompileresult',
            name='code_compile',
        ),
        migrations.RemoveField(
            model_name='codecompile',
            name='user',
        ),
        migrations.AddField(
            model_name='codecompile',
            name='is_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='codecompile',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codecompile',
            name='stdout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codecompile',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CodeCompileResult',
        ),
    ]
